"""Add token usage table

Revision ID: 6276a0473116
Revises: ae0eecc43ed6
Create Date: 2025-05-11 18:52:47.050200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6276a0473116'
down_revision: Union[str, None] = 'ae0eecc43ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('interaction_id', sa.String(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_logs_agent_id'), 'token_usage_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_id'), 'token_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_interaction_id'), 'token_usage_logs', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_message_id'), 'token_usage_logs', ['message_id'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_timestamp'), 'token_usage_logs', ['timestamp'], unique=False)
    op.add_column('chat_messages', sa.Column('interaction_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_chat_messages_interaction_id'), 'chat_messages', ['interaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_interaction_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'interaction_id')
    op.drop_index(op.f('ix_token_usage_logs_timestamp'), table_name='token_usage_logs')
    op.drop_index(op.f('ix_token_usage_logs_message_id'), table_name='token_usage_logs')
    op.drop_index(op.f('ix_token_usage_logs_interaction_id'), table_name='token_usage_logs')
    op.drop_index(op.f('ix_token_usage_logs_id'), table_name='token_usage_logs')
    op.drop_index(op.f('ix_token_usage_logs_agent_id'), table_name='token_usage_logs')
    op.drop_table('token_usage_logs')
    # ### end Alembic commands ###