"""Add chat_messages table fix

Revision ID: 76afca9d0786
Revises: 42718177f57c
Create Date: 2025-04-29 00:21:59.771997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76afca9d0786'
down_revision: Union[str, None] = '42718177f57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

sender_type_enum = postgresql.ENUM('USER', 'AGENT', 'SYSTEM', name='sender_type_enum', create_type=False)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sender_type_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('chat_messages', 'sender_type',
               existing_type=sa.VARCHAR(),
               type_=sender_type_enum,
               existing_nullable=False,
               postgresql_using='sender_type::sender_type_enum')
    op.alter_column('agent_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_chat_messages_channel', table_name='chat_messages')
    op.drop_constraint('chat_messages_agent_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'agent_configs', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_agent_id_fkey', 'chat_messages', 'agent_configs', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_chat_messages_channel', 'chat_messages', ['channel'], unique=False)
    op.alter_column('chat_messages', 'sender_type',
               existing_type=sender_type_enum,
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='sender_type::varchar')
    sender_type_enum.drop(op.get_bind(), checkfirst=True)
    op.alter_column('agent_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###