"""Add agent user authorization and rename owner id

Revision ID: 6725e4a32163
Revises: 51cbd1cf792d
Create Date: 2025-04-30 17:18:30.544361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6725e4a32163'
down_revision: Union[str, None] = '51cbd1cf792d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Создаем новую таблицу agent_user_authorizations
    op.create_table('agent_user_authorizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('agent_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('is_authorized', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agent_configs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('agent_id', 'user_id', name='uq_agent_user_authorization')
    )
    op.create_index(op.f('ix_agent_user_authorizations_agent_id'), 'agent_user_authorizations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_user_authorizations_is_authorized'), 'agent_user_authorizations', ['is_authorized'], unique=False)
    op.create_index(op.f('ix_agent_user_authorizations_user_id'), 'agent_user_authorizations', ['user_id'], unique=False)

    # 2. Добавляем новую колонку owner_id, временно разрешая NULL
    op.add_column('agent_configs', sa.Column('owner_id', sa.String(), nullable=True))

    # 3. Копируем данные из старой колонки user_id в новую owner_id
    op.execute('UPDATE agent_configs SET owner_id = user_id WHERE user_id IS NOT NULL')
    # Примечание: Если user_id мог быть NULL, и вам нужно дефолтное значение для owner_id, добавьте:
    # op.execute("UPDATE agent_configs SET owner_id = 'default_owner_id' WHERE owner_id IS NULL")

    # 4. Делаем новую колонку owner_id NOT NULL
    op.alter_column('agent_configs', 'owner_id', nullable=False)

    # 5. Создаем индекс для новой колонки owner_id
    op.create_index(op.f('ix_agent_configs_owner_id'), 'agent_configs', ['owner_id'], unique=False)

    # 6. Удаляем старую колонку user_id и ее индекс
    op.drop_index('ix_agent_configs_user_id', table_name='agent_configs')
    op.drop_column('agent_configs', 'user_id')

    # 7. Удаляем колонку is_authorized из таблицы users и ее индекс
    op.drop_index('ix_users_is_authorized', table_name='users')
    op.drop_column('users', 'is_authorized')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Добавляем обратно is_authorized в users и ее индекс
    # Убедитесь, что server_default='false' соответствует вашей логике
    op.add_column('users', sa.Column('is_authorized', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('ix_users_is_authorized', 'users', ['is_authorized'], unique=False)

    # 2. Добавляем обратно колонку user_id, временно разрешая NULL
    op.add_column('agent_configs', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))

    # 3. Копируем данные из owner_id в user_id
    op.execute('UPDATE agent_configs SET user_id = owner_id')

    # 4. Делаем user_id NOT NULL (если она была NOT NULL до этого)
    op.alter_column('agent_configs', 'user_id', nullable=False)

    # 5. Создаем индекс для user_id
    op.create_index('ix_agent_configs_user_id', 'agent_configs', ['user_id'], unique=False)

    # 6. Удаляем колонку owner_id и ее индекс
    op.drop_index(op.f('ix_agent_configs_owner_id'), table_name='agent_configs')
    op.drop_column('agent_configs', 'owner_id')

    # 7. Удаляем таблицу agent_user_authorizations и ее индексы
    op.drop_index(op.f('ix_agent_user_authorizations_user_id'), table_name='agent_user_authorizations')
    op.drop_index(op.f('ix_agent_user_authorizations_is_authorized'), table_name='agent_user_authorizations')
    op.drop_index(op.f('ix_agent_user_authorizations_agent_id'), table_name='agent_user_authorizations')
    op.drop_table('agent_user_authorizations')

    # ### end Alembic commands ###